### PR TITLE
[docs] update getting-started to work with cosign 2.1

### PR DESCRIPTION
**Pull request by NissesSenap**
#### Summary

Trying to follow the getting started guide is currently rather hard due to the cosign version used is rather old.
To make it easier I updated the documentation.

#### Release Note

NONE

### CODE REVIEW

**Comment by NissesSenap** [comment]
I have tested all the commands with cosign version `2.1.0` I chose not to update the example output, personally I think it's close enough, and I think people will understand.

I also tried to run with cosign `2.2.0`, but then I got the following error

```txt
Handling connection for 8080
Error: signing registry.local:5001/sigstore/demo@sha256:95bb686784c1d0deafc656486ae562e0420ab2b9a2f4c307a6571d401ce00e3e: [POST /api/v1/log/entries][422] createLogEntry default  &{Code:422 Message:invalid kind value: "dsse"}
main.go:74: error during command execution: signing registry.local:5001/sigstore/demo@sha256:95bb686784c1d0deafc656486ae562e0420ab2b9a2f4c307a6571d401ce00e3e: [POST /api/v1/log/entries][422] createLogEntry default  &{Code:422 Message:invalid kind value: "dsse"}
```

I'm 90% sure this is due to https://github.com/sigstore/cosign/pull/3113.

I think this PR is better than the current state, but ideally it should work with 2.2.0.
Furthermore, I feel that I'm a bit out of depth trying to debug why this happens, but looking at the PR it seems to be a change in the way of working.
If anyone with more knowledge about the `dsse` change, please share.

File: getting-started.md [hunk 1]
```diff
@@ -61,13 +66,15 @@ b1e3f3238f7a   registry:2                        "/entrypoint.sh /etc…"   15 m
...
 ```shell
 docker rm -f b1e3f3238f7a
 ```
 
 # Install sigstore-scaffolding pieces
 
 ## From the release
+
 ```shell
 curl -Lo /tmp/setup-scaffolding-from-release.sh https://github.com/sigstore/scaffolding/releases/download/v0.6.4/setup-scaffolding-from-release.sh
```
Comment (bobcallaway) [inline getting-started.md:79]:
```suggestion
curl -Lo /tmp/setup-scaffolding-from-release.sh https://github.com/sigstore/scaffolding/releases/download/v0.6.9/setup-scaffolding-from-release.sh
```

this should fix the DSSE issue and allow cosign v2.2.0 to work

**Comment by NissesSenap** [comment]
Thanks for the fix @bobcallaway , I was at PTO so that why I was so slow to update.
Is there anything else needed for the PR you feel?

**Review by bobcallaway — APPROVED** [review]
